2021-08-04 22:57:08,678 DEBUG    root            Loaded Command Group: ['gcloud', 'container']
2021-08-04 22:57:08,694 DEBUG    root            Loaded Command Group: ['gcloud', 'container', 'clusters']
2021-08-04 22:57:08,701 DEBUG    root            Loaded Command Group: ['gcloud', 'container', 'clusters', 'list']
2021-08-04 22:57:08,725 DEBUG    google.auth.transport.requests Making request: GET http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/416357049773-compute@developer.gserviceaccount.com/?recursive=true
2021-08-04 22:57:08,729 DEBUG    urllib3.connectionpool Starting new HTTP connection (1): metadata.google.internal:80
2021-08-04 22:57:08,731 DEBUG    urllib3.connectionpool http://metadata.google.internal:80 "GET /computeMetadata/v1/instance/service-accounts/416357049773-compute@developer.gserviceaccount.com/?recursive=true HTTP/1.1" 200 196
2021-08-04 22:57:08,732 DEBUG    google.auth.transport.requests Making request: GET http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/416357049773-compute@developer.gserviceaccount.com/token
2021-08-04 22:57:08,754 DEBUG    urllib3.connectionpool http://metadata.google.internal:80 "GET /computeMetadata/v1/instance/service-accounts/416357049773-compute@developer.gserviceaccount.com/token HTTP/1.1" 200 259
2021-08-04 22:57:08,779 DEBUG    google.auth.transport.requests Making request: GET http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/416357049773-compute@developer.gserviceaccount.com/?recursive=true
2021-08-04 22:57:08,781 DEBUG    urllib3.connectionpool Starting new HTTP connection (1): metadata.google.internal:80
2021-08-04 22:57:08,783 DEBUG    urllib3.connectionpool http://metadata.google.internal:80 "GET /computeMetadata/v1/instance/service-accounts/416357049773-compute@developer.gserviceaccount.com/?recursive=true HTTP/1.1" 200 196
2021-08-04 22:57:08,783 DEBUG    google.auth.transport.requests Making request: GET http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/416357049773-compute@developer.gserviceaccount.com/token
2021-08-04 22:57:08,786 DEBUG    urllib3.connectionpool http://metadata.google.internal:80 "GET /computeMetadata/v1/instance/service-accounts/416357049773-compute@developer.gserviceaccount.com/token HTTP/1.1" 200 259
2021-08-04 22:57:08,832 DEBUG    root            Running [gcloud.container.clusters.list] with arguments: []
2021-08-04 22:57:08,863 DEBUG    root            (gcloud.container.clusters.list) ResponseError: code=403, message=Request had insufficient authentication scopes.

If you are in a compute engine VM, it is likely that the specified scopes during VM creation are not enough to run this command.
See https://cloud.google.com/compute/docs/access/service-accounts#accesscopesiam for more information about access scopes.
See https://cloud.google.com/compute/docs/access/create-enable-service-accounts-for-instances#changeserviceaccountandscopes for how to update access scopes of the VM.
Traceback (most recent call last):
  File "/usr/local/google-cloud-sdk/lib/surface/container/clusters/list.py", line 76, in Run
    clusters = adapter.ListClusters(project, location)
  File "/usr/local/google-cloud-sdk/lib/googlecloudsdk/api_lib/container/api_adapter.py", line 2674, in ListClusters
    return self.client.projects_locations_clusters.List(req)
  File "/usr/local/google-cloud-sdk/lib/googlecloudsdk/third_party/apis/container/v1/container_v1_client.py", line 548, in List
    config, request, global_params=global_params)
  File "/usr/local/google-cloud-sdk/lib/third_party/apitools/base/py/base_api.py", line 737, in _RunMethod
    return self.ProcessHttpResponse(method_config, http_response, request)
  File "/usr/local/google-cloud-sdk/lib/third_party/apitools/base/py/base_api.py", line 743, in ProcessHttpResponse
    self.__ProcessHttpResponse(method_config, http_response, request))
  File "/usr/local/google-cloud-sdk/lib/third_party/apitools/base/py/base_api.py", line 610, in __ProcessHttpResponse
    http_response, method_config=method_config, request=request)
apitools.base.py.exceptions.HttpForbiddenError: HttpError accessing <https://container.googleapis.com/v1/projects/sap-gtlc-devops/locations/-/clusters?alt=json>: response: <{'www-authenticate': 'Bearer realm="https://accounts.google.com/", error="insufficient_scope", scope="https://www.googleapis.com/auth/cloud-platform"', 'vary': 'Origin, X-Origin, Referer', 'content-type': 'application/json; charset=UTF-8', 'date': 'Wed, 04 Aug 2021 22:57:08 GMT', 'server': 'ESF', 'cache-control': 'private', 'x-xss-protection': '0', 'x-frame-options': 'SAMEORIGIN', 'x-content-type-options': 'nosniff', 'transfer-encoding': 'chunked', 'status': '403', 'content-length': '479', '-content-encoding': 'gzip'}>, content <{
  "error": {
    "code": 403,
    "message": "Request had insufficient authentication scopes.",
    "status": "PERMISSION_DENIED",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.ErrorInfo",
        "reason": "ACCESS_TOKEN_SCOPE_INSUFFICIENT",
        "domain": "googleapis.com",
        "metadata": {
          "service": "container.googleapis.com",
          "method": "google.container.v1.ClusterManager.ListClusters"
        }
      }
    ]
  }
}
>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 984, in Execute
    resources = calliope_command.Run(cli=self, args=args)
  File "/usr/local/google-cloud-sdk/lib/googlecloudsdk/calliope/backend.py", line 809, in Run
    resources = command_instance.Run(args)
  File "/usr/local/google-cloud-sdk/lib/surface/container/clusters/list.py", line 134, in Run
    raise exceptions.HttpException(error, util.HTTP_ERROR_FORMAT)
googlecloudsdk.calliope.exceptions.HttpException: ResponseError: code=403, message=Request had insufficient authentication scopes.
2021-08-04 22:57:08,865 ERROR    root            (gcloud.container.clusters.list) ResponseError: code=403, message=Request had insufficient authentication scopes.

If you are in a compute engine VM, it is likely that the specified scopes during VM creation are not enough to run this command.
See https://cloud.google.com/compute/docs/access/service-accounts#accesscopesiam for more information about access scopes.
See https://cloud.google.com/compute/docs/access/create-enable-service-accounts-for-instances#changeserviceaccountandscopes for how to update access scopes of the VM.
